### ISSUE TITLE
Cursor of external mouse keeps jumping to bottom right corner of screen in Gaming Mode (Steam Deck UI)

### ISSUE THREAD

**Issue by benstor214** [ValveSoftware/SteamOS#1093]
#### Your system information

* Steam client version: 1687386907
* SteamOS version: 3.4.8
* Opted into Steam client beta?: No]
* Opted into SteamOS beta?: No 
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
When using an external mouse In Gaming Mode, the cursor constantly disappears after 5 seconds and jumps to the bottom right.

#### Steps for reproducing this issue:

1. Put the Steam Deck in the dock (Valve Docking Station) with an external mouse attached
2. Power on the Steam Deck
3. Don't touch the mouse for 5 seconds

I can't believe I couldn't find this issue already in the tracker. Maybe I just missed it? If so, this issue should be closed (of course).

**Comment by realeldermann** [comment]
I have the same problem with the same setup.

**Comment by unclejack** [comment]
This might be related to some previous issues with elements of the UI being highlighted for no obvious reason due to the presence of the invisible cursor in that region. The cursor might be moved to a corner to avoid that particular problem.

This makes things a bit more difficult when a mouse/touchpad is attached. That would have to be handled differently.

**Comment by pauljtremblay** [comment]
Not sure where to file this bug, but I found this ticket trying to search the same problem with the steam app on a windows 11 gaming laptop. After steam launches the mouse cursor is continually pulled into the bottom right side of the screen. While this happens, it is not possible to navigate the menu via keyboard shortcuts, so this is both incredibly annoying and an a11y (accessibility) issue.

An external mouse is also in use.

The steam.exe properties reports the version as `8.18.16.37`.

**Comment by leewiscovitch** [comment]
Sames here as well...jsaux dock, mouse plugged in (in my case it's routing through a KVM switch), and constantly going to bottom-right.

There is a fairly long reddit thread about others experiencing it too:

https://www.reddit.com/r/SteamDeck/comments/12ct3uf/when_using_a_mouse_in_gaming_mode_cursor/

**Comment by HoodBlah** [comment]
I have the same set up as leewiscovitch. After restarting the deck everything seems to be working, but the mouse does disappear after a few seconds of not moving. But atleast when I move it again it is still in the same spot I left it. Sometimes it does go to the corner if unattended for more than 20 seconds though.

**Comment by jcheynel** [comment]
Same problem here using my Lenovo docking station and just any mouse I've tried...

**Comment by Levistras** [comment]
Open for 3 months with no traction?

**Comment by loboaureo** [comment]
Still happening, with last stable version and a logitech pebble mouse via bluetooth

**Comment by benstor214** [comment]
Hello? Is there anyone out there? It’s been over 3 months and no-one has been assigned yet.

**Comment by max0r4axor** [comment]
Mine is doing the same thing just snaps to the bottom right corner its a bluetooth mouse

**Comment by neverw1nter** [comment]
Started today out of the blue. Wired Roccat mouse with original Steam Dock.

**Comment by Jim-Jaspers** [comment]
This happens to me with the official dock and wired mice, it's super annoying!

**Comment by max0r4axor** [comment]
I don't think it has anything to do with a dock or a mouse wired or wireless / Bluetooth. It definitely software related. I almost bet it has something to do with mouse emulation. Kinda acts like it wants to rehome to 0,0 every so often.

**Comment by krompus** [comment]
I have this issue with the official dock and a USB mouse, it's very annoying and disorienting, I hope it can be fixed soon. Perhaps the pointer could be rendered invisible when idle instead of displaced?

**Comment by Levistras** [comment]
I'll add to the thread that it also happens with a Logitech Unifying Receiver.  I'm using a wireless keyboard that has a built-in trackpad via a Unifying Receiver and issue happens there.   In my case using the official Steam Dock

**Comment by anegoda1995** [comment]
same for me
mouse: MX Master 3S

**Comment by TacoDelPaco** [comment]
+1

Steam Dock, using the Steam Beta (main) I was hoping a newer version would fix it.

Is this a relatively new issue, or has this always happened?

I noticed if you click without moving the mouse after it disappears, it will go back to where it originally was.

**Comment by eakse** [comment]
My mouse is connected through Bluetooth, Deck is docked, same issue...

**Comment by LunarStargate** [comment]
I have had the mouse move to the upper left whenever I click on something, most noticeable when running desktop apps in game mode like chrome. Ive noticed it on all channels of steam OS. Bluetooth and USB connections act the same

**Comment by krompus** [comment]
> I have had the mouse move to the upper left whenever I click on something, most noticeable when running desktop apps in game mode like chrome. Ive noticed it on all channels of steam OS. Bluetooth and USB connections act the same

That's unrelated, you are referring to a Gamescope issue where it focuses subwindows and popups within the app and resets the cursor to top left. I had that issue with Firefox, try hovering over a tab and it happens when the little mouseover popup appears. Workaround is adding the Nested Desktop entry from Desktop Mode as a non-Steam game, launching that in Game Mode and launching the affected apps in there.

This reset to bottom right is without Gamescope (in game mode view without a game open), after a few seconds of no input, the cursor disappears and when you input cursor again it has been teleported to bottom right.

**Comment by LunarStargate** [comment]
> > I have had the mouse move to the upper left whenever I click on something, most noticeable when running desktop apps in game mode like chrome. Ive noticed it on all channels of steam OS. Bluetooth and USB connections act the same
> 
> That's unrelated, you are referring to a Gamescope issue where it focuses subwindows and popups within the app and resets the cursor to top left. I had that issue with Firefox, try hovering over a tab and it happens when the little mouseover popup appears. Workaround is adding the Nested Desktop entry from Desktop Mode as a non-Steam game, launching that in Game Mode and launching the affected apps in there.
> 
> This reset to bottom right is without Gamescope (in game mode view without a game open), after a few seconds of no input, the cursor disappears and when you input cursor again it has been teleported to bottom right.

Understood. I've noticed today the difference between the 2 issues

**Comment by ronw623** [comment]
+1
Steam Deck Limited Edition - Stable build
Using MX Master 3 or iClever folding KB/mouse combo while scrolling through my library in game mode

**Comment by seanmten** [comment]
512GB LCD, MX Master 3 as well. I've tried stable, beta, and preview with no changes. This has been happening for months.

**Comment by oczki** [comment]
Same issue - mouse cursor jumps to bottom right corner after 2-3 seconds of inactivity. Using most recent stable software on 512 GB LCD version. Applies only to gaming mode; desktop mode is not affected.

**Comment by blind133** [comment]
I started having this issue out of the blue. 
No dock. Wireless Bluetooth mouse (Logitech triathlon 710) paired through decky bluetooth plugin. Exact same issue, mouse cursor teleports to bottom right corner every few seconds. 

It's making games unplayable. 

Most recent stable build 3.5.7 / 20231122.1

**Comment by Sunspark-007** [comment]
I have this issue too. It appears to trigger when hovering the cursor over the buttons at the bottom of the screen when the steam panel that slides open from the left side is open.. when you move the cursor to a lit button it suddenly likes to reappear in the bottom right.

**Comment by WolfPD** [comment]
Same issue here (original Steam Dock; wired Logitech trackball)

**Comment by Noblesavag3** [comment]
I also have the same mouse issue and have had it for a while.

This mouse bug persists in my OS version.

**Your system information**

    Steam client version: 1705108172
    SteamOS version: 3.5.7
    Opted into Steam client beta?: No
    Opted into SteamOS beta?: No
    Have you checked for updates in Settings > System?: Yes

**Comment by atillalifeson** [comment]
Commenting to highlight this issue for it hopefully gaining traction since it's really open for a lot of months.

I use the SteamDeck regularly on my desk on dock attached to an external display (had the original dock and a 3rd party dock).

I am constantly using the Gaming Mode since it's more minimal, has performance benefits and M/KB are working and supported. As perfectly described by others already the mouse cursor is constantly homing in on the bottom right when not in use (most of the time if you pause your mouse movements because you are reading posts, comments or just the store page of a game).

I understand why this behaviour might be intended. Gaming mode is heavily controller oriented which I like it to stay that way (my Xbox Series X Controller is also connected simultaneously with the M/KB when in use). The disappearance of the cursor ultimately gives the controller the priority whatever happens. Which is understandable because of the nature of Gaming Mode.

One solution could be, to give input priority or an "active state" to the IO device that made the last input even if multiple are attached.

Would love this to gain some traction since it's really hindering the UX in Gaming Mode.

**Comment by TacoDelPaco** [comment]
Just wanted to update that it seems this has been fixed for the most part in the latest builds, what I've noticed is using Desktop Mode with Big Picture Mode there are no issues I can find whatsoever; the mouse cursor stays put, scrolling works, etc.

Although directly using Gaming Mode on the Steam Deck seems to still have scrolling issues (you can't scroll if the mouse moves), the mouse cursor seems to be remembering where it last was which seems like things are finally moving in the right direction.

```
OS Variant: steamdeck-main
OS Version: 3.6
OS Build: 20240221.1000
Kernel Version: 6.1.52-valve17-1-neptune-61
Dock Firmware Version: 0.13.15.123
```

**Comment by Xobtah** [comment]
I'm on the latest build and the mouse still goes to the bottom right corner

**Comment by Barhwald** [comment]
The bug is still there. I’ve just connected my Logitech MX anywhere 3s and the cursor is still being teleported to bottom right corner, which is really annoying. Any chances it will be fixed?

**Comment by alekmar** [comment]
I have the same problem. 

But the same behavior is when you don't use a dock and/or an external mouse. Try this: go to the main screen in the game mode, press left "STEAM" button and move coursor by right touchpad. Coursor goes to right corner after ~5 seconds. 

Therefore, I think SD or dock has a problem to recognize that we pluged in an external device and SD still works in a "normal" mode (like without an external device). Actually, this is the issue.

My official valve dock can't recognize my external mouse correctly, but when I had another dock (3rd party), it recognized my mouse properly and I didn't have this problem

**Comment by fjordBob** [comment]
The thread is now almost a year old and no developer or anyone else from Stream has commented on it. Either they don't care or it's not fixable. But it would be a nice move from Stream to at least make some kind of statement about it. Is there another level of escalation besides opening a ticket?

**Comment by intrasp3ctre** [comment]
I'm also having this issue

**Comment by atillalifeson** [comment]
In addition to the persisting unintuitive mouse behavior experienced by frequent SteamDeck users like myself, who rely on it as either a secondary or primary desktop environment and heavily utilize GameMode for its superior performance and customization options compared to Desktop Mode, there's another perplexing issue that I believe warrants attention, despite its direct association with mouse functionality.

As far as I can recall, there seems to be an occurrence of an invisible overlay appearing over the UI when GameMode is activated. This results in the standard Big Picture cursor being replaced by the cursor configured in Desktop Mode. This overlay suspicion arises from the cursor changing to the window-resizing cursor when moved to the screen edges. Strangely, right-clicking triggers a small KDE printer popup window, leading to a printing dialog after selecting "print". This anomaly was first noticed with the introduction of SteamOS 3.5.17.

This observation is based on my experience of having to perform a complete reset of my SteamDeck using the officially provided recovery image, where this issue was absent in the older version of SteamOS included in the recovery image. Upon updating to SteamOS 3.5.17 again, this strange invisible "overlay" reappeared, along with the replacement of the Big Picture cursor by the current Desktop cursor (possibly due to the overlay taking precedence).

However, despite these technical details, the problem of the mouse cursor unexpectedly jumping to the bottom right corner after a few seconds persists. This behavior feels far from "normal" and significantly disrupts my browsing experience in the library or store, particularly when using Game Mode with a keyboard and mouse attached. Pausing to read game descriptions is especially frustrating, as the sudden jump interrupts scrolling ability.

I find it puzzling that many SteamDeck owners seem unfazed by this obvious and disruptive mouse behavior in Game Mode. For users like myself, who view the SteamDeck as a versatile Linux desktop computer with advanced gaming capabilities and always have a keyboard and mouse attached, this issue severely diminishes the overall experience.

I also want to apologise if this additional mouse related problem would need another issue opened and would do so if requested.

![1](https://github.com/ValveSoftware/SteamOS/assets/82589605/deda5005-351d-4f23-be14-b89054049db0)
![2](https://github.com/ValveSoftware/SteamOS/assets/82589605/4e56d8c5-ea10-477a-90c0-cb06263a0e20)
![3](https://github.com/ValveSoftware/SteamOS/assets/82589605/93bbc458-78a8-43ba-8bd8-bb1346fce487)
![4](https://github.com/ValveSoftware/SteamOS/assets/82589605/d04fbd6d-1bb6-427c-ba9d-2ab370bbb5c1)
![5](https://github.com/ValveSoftware/SteamOS/assets/82589605/bb6048ae-7686-4134-889c-b89993ca4216)
[output.pdf](https://github.com/ValveSoftware/SteamOS/files/14970733/output.pdf)

**Comment by atillalifeson** [comment]
The mouse is still jumping to the bottom right after 5 seconds of no interaction disrupting the navigation while browsing the library or the store. Even scrolling is not possible after the mouse relocates to the bottom right. I'm currently on SteamOS 3.5.17 Stable.

**Comment by Veckler** [comment]
I'm leaving a comment to show that I also suffer from this issue.

**Comment by Metroids224** [comment]
This issue happens in every browser in game mode, with no dock, just the Steam deck controls. Mouse jumps to top left and program seems to refresh after ~3 seconds of inactivity. Left click commands work properly, right click commands seem to bring program out and in to fullscreen, and resets the cursor to the top left of the window.

**Comment by KirbyQK** [comment]
Also having this issue with a Logitech MX Master 3S connected via Bluetooth. I'm on OS 3.5.19 with an OLED. Noticed it a lot in the menus, using webcord or Firefox in gaming mode or playing Civ V. Recently started streaming my modded Minecraft instance to my deck and it's REALLY annoying - something like 80% of the time when I leave an inventory it snaps the cursor down.

**Comment by steviebwoy** [comment]
This is happening for me too. Standard keyboard and mouse in docked mode. Cannot believe this hasn't been fixed as its such a fundamental flaw. It means that the mouse is useless, as it flicks to the bottom right of the screen every 3 seconds. Noticed that the same issue prevails in games as well. It's so annoying. The only solution I've found is to use desktop mode but really, this is very very poor. I'd imagine a fix would take a few hours to implement, and yet we've had no solution after over a year. Very poor. Especially given the impact is massive and the fix is so straight forward.

**Comment by dumplinghusky** [comment]
Seeing this issue also

**Comment by andymccall** [comment]
Commenting on this issue.  Makes the Desk almost useless with a mouse, so docked mode on a monitor is pointless.

**Comment by dtcmaker** [comment]
Same.  Valve Steam Deck Docking Station.  Logitech M325 mouse.

Deck version = F7A0120, dock version = 0.13.15.121

**Comment by leewiscovitch** [comment]
Wanted to leave a snarky comment...instead just sold my steamdeck

**Comment by Tamas1337** [comment]
This is ridiculous Valve, not fixing this for over a year, can't be that hard can it? This device is great but problems like this really grinds my gears as if I were to shift a car without using the clutch at all...

**Comment by benstor214** [comment]
I don’t know… I’m partially blaming myself for this.
This issue should have been opened by someone more likable.
Maybe the best forward action would be to close this issue as not planned and for someone else to open a separate issue?

**Comment by krompus** [comment]
> Maybe the best forward action would be to close this issue as not planned and for someone else to open a separate issue?

There's nothing wrong with this issue, please do not delete it and/or open a duplicate.

**Comment by atillalifeson** [comment]
> Maybe the best forward action would be to close this issue as not planned and for someone else to open a separate issue?

No, as stated before leave it open. Back when I first commented I was about to open a new issue but it is strictly stated to not create another issue if there is already one existing and describing the same problem.

You did everything right.

And to not let this here end up only as a comment: the problem **still** persists.

OS Version: 3.5.19
OS Build: 20240422.1

**Comment by fjordBob** [comment]
I think we have to understand valve's predicament. Less than [400 people have to bring more than $400 million](https://www.techspot.com/news/103825-court-documents-leak-valve-gross-pay-surprisingly-low.html) to the people. There's no time left to fix bugs. If I were to be spiteful, I would say that valve's behaviour reminds me of [this](https://en.wikipedia.org/wiki/Money_for_Nothing_(song)) song.

**Comment by benstor214** [comment]
Just no. They may ignore me - for reasons that elude me. But they are doing a lot. Just look at proton!

**Comment by TescoCatalogue** [comment]
Just got my steamdeck a few weeks ago. I noticed this issue and went looking for a fix and this is the first thread I found about it. I have the same isssue as everyone else: gaming mode, Bluetooth mouse, mouse cursor jumping to bottom right corner of screen every few seconds.

**Comment by roelvermeulen** [comment]
Same problem here. When in desktop mode, it works fine, but when in gaming mode the mouse cursor goes to the bottom right corner of the screen every second or so when inactive for a very short time. Also, but do not know if this is related, there is a delay in the scrolling wheel. The first scroll never works and I have to scroll the wheel several steps to make it start scrolling, which makes for a not very fluid interaction with the interface. I am using a dock with a Logitech dangle attached that connects to my wireless keyboard and mouse.

**Comment by TheGhostOfSmittyWerbenjagermanjensen** [comment]
Also having this issue. 

OS Version: 3.5.19
OS Build: 20240422.1

I'm not very familiar with Github - does the fact that issue #1533 (duplicate issue) was closed by a Valve employee as "Not Planned" mean they are aware of this behavior, don't consider it an issue, and aren't going to fix it? It makes the docked game mode UI incredibly annoying to navigate with a mouse.

**Comment by kisak-valve** [comment]
Hello @TheGhostOfSmittyWerbenjagermanjensen, the choice of wording there is GitHub's with the tooltip reading it should be used for "Won't fix, can't repro, duplicate, stale". There is no further meaning that should be read into that one way or another, just that a duplicate issue report was closed as a duplicate.

**Comment by trebarg** [comment]
Same issue here.  On stable release on my 512GB OLED.   This has been happening in game mode when scrolling in my library for as long as I can remember.   It is fine in games and fine in desktop mode.   Logitech M 650 L connected via Bluetooth.

**Comment by ajuntari** [comment]
I'd like to chime in and report the same issue happening in the Gaming Mode with a wired mouse connected to Steam Deck via USB-C dongle. The Steam Deck is LCD 512GB version, and the mouse is Coolermaster MM720. The cursor doesn't display this behavior while in Desktop mode.

**Comment by krompus** [comment]
I'm on Stable branch, I've tested a bit more. It seems that the cursor will sometimes reappear in the same spot, and sometimes it will teleport to the bottom right, it's unclear what causes this inconsistent behaviour, but I would encourage @Veckler to keep testing to see if they see the same behaviour or if it's truly resolved on beta branch. I have noticed another related issue: mouse scrolling input does not prevent the cursor from disappearing, so often I'll be scrolling a page and it will stop scrolling because the cursor has disappeared and teleported to the bottom right.

**Comment by atillalifeson** [comment]
> I'd like to report that currently I don't experience the issue.

I just switched over to the beta branch, installed the most recent update and can confirm that the cursor is indeed reappearing at the same spot where it disappeared.

This is extremely refreshing being able to scroll through store titles or comments, stopping, reading and being able to scroll further while having the cursor behave as expected.

One thing I realised though:
After the cursor disappears you are only able to use the scroll wheel if the cursor reappears again. It would be great if scrolling would also work when the cursor is hidden but that's just nitpicking at this point. I'm glad that this got picked up. Can't wait to see this carry over to the stable channel.

Steam client version: 1726683985
SteamOS version: 3.6.13
Opted into Steam client beta?: Yes
Opted into SteamOS beta?: No
Have you checked for updates in Settings > System?: Yes

**Comment by Pffzzhh** [comment]
I really hope this will be fixed soon!
I use the Steam Deck often with monitor + mouse + keyboard, and its very frustrating, that the mouse is loosing its position, as the scrolling does not functions properly.

**Comment by TheGhostOfSmittyWerbenjagermanjensen** [comment]
I think the main conflict here is that the way people expect a traditional mouse cursor to work doesn't match the "ideal" set of behaviors for the trackpad-controlled cursor. 

The Steam Deck should have two sets of context-sensitive cursor behaviors, dependent on if the user is controlling the cursor with an external mouse or with the built-in trackpad. 

1) Trackpad in use? Cursor behaves as it does currently. 
2) External mouse in use? Cursor behaves as it does in desktop mode, even while in gaming mode.

**Comment by shad0wpan** [comment]
I am having this and other mousing issues. I have had my 256LCD steamdeck for two months, and have tried three different bluetooth mice and one wired mouse and all perform the same. My current mouse is a multi-mode, so I have also tried it using the 2.4ghz dongle, with the same results. Any lack of mouse movement greater than 5 seconds has the cursor dissappear and once the mouse is moved, it comes from the bottom right. Also, when I am trying to scroll in any window, app or webpage, the scroll wheel sends you all the way to the bottom with the slightest touch to the scroll wheel, or all the way to the top in the opposite direction, no matter the length of the page. I have to click and drag the sidebar to scroll. I attempted to open the KDE mouse settings module, but it gave me an error message: "Querying input devices failed. Please reopen this settings module." No other settings module produces this error message. I am not particularly experienced with Linux and less with KDE(always used GNOME before), so I am unsure about further troubleshooting, and my google-fu has largely failed me in this instance. I have not, however, had any problems with lag, tracking errors, or click response with any mouse. Aside from the above mentioned, everything else works fine with the mouse. I ran a steamdeck self-diagnostic from the gaming mode, but it just gave me 12 pages of code. Here is my system config from Desktop Mode. 
![image](https://github.com/user-attachments/assets/df77d7c5-bb96-4784-a18e-7207f57504d8)

**Comment by ffrggyg** [comment]
They almost fixed it in 3.6.19!!! Now scrolling works fine and the cursor disappears, but doesn't reset its position!

**Comment by atillalifeson** [comment]
I can also _**confirm**_ after the testing the beta branch that 3.6.19 on the stable channel fixes the disappearing and relocating mouse cursor.

Once the cursor is not visible even hover effects lose the focus. Scrolling while the cursor is not visible is not possible though.

But:
The cursor always reappears at the _**exact**_ location it disappeared. This makes scrolling through store pages and comments feel natural again.

Thanks a ton for the devs for addressing this. It came one and a half years later but better late than never, right? 😬

It really rounds up the experience in game mode on a desktop setting now. Thank you!

Thanks also to @kisak-valve for keeping this issue focused on this particular thread.

**Comment by WyattAlexander-001** [comment]
Currently on 3.7.19 stable, scrolling with several mice for testing. 

In library it stutters, cursor disappears during scroll and reappears after a few scrolls after stopping my ability to scroll. Will snap up halfway after have the expected scroll length.

Eg. Scroll ten rows, but snap back to row 5 of library.

Scrolling is fine in settings, cursor does not disappear.

Scrolling in Home is fine though there's minimal height in the home menu.

Scrolling in store after an empty search, scroll works for up to 6 consecutive up or down scrolls and no snap back.

Is this issue still being tracked?
