### ISSUE TITLE
Remote Play not working on Steam Deck game mode

### ISSUE THREAD

**Issue by mctricks** [ValveSoftware/SteamOS#1148]
#### Your system information

* Steam client version: 1695085405
* SteamOS version: 3.5
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: Preview 
* Have you checked for updates in Settings?: Yes
* Hardware: Steam Deck 

#### Please describe your issue in as much detail as possible: Remote Play isn't working in game mode. After switching to the preview update channel, launching a remote play session opens the game on the host PC, but the deck stays stuck on the "loading" screen (the one with the "abort" button in the bottom right). The game's audio does play on the deck, but no visuals other than the SteamOS loading screen. No combination of host and client option changes I've tried have remedied the issue. Reverting to the stable branch (3.4.10) fixes the issue. 

Remote Play does still work as expected when switching into desktop mode.

#### Steps for reproducing this issue:

1. Update to 3.5
2. Launch any remote play session
3. The game will launch, and the audio will come through, but the SteamOS loading screen stays up indefinitely

**Comment by krittinen** [comment]
I can replicate this with preview 3.5 as well.

**Comment by calebwuethrich** [comment]
Experienced same behavior in both beta and preview channels.

**Comment by Rephlexion** [comment]
All this ^ plus even back on stable 3.4, I'm getting intermittent freeze-frames where the controls and audio still work, but the screen is stuck on a frame until I hit the Steam button once or twice to get the stream to refresh... and audio drops out quite consistently after 5-30 minutes... AND it seems to be impossible to close the game stream from the Deck; it just hangs on a black screen -- but I'm pretty sure the game is actually closed on the host PC.

**Comment by safijari** [comment]
Streaming from a host PC to the Deck is fixed in the latest update that was pushed to preview this morning. Streaming from the Deck to my windows Desktop also works. Streaming from the Deck to my samsung phone using the Steam Link app does not work. Screenshot crash mentioned in https://github.com/ValveSoftware/gamescope/issues/961 still happens

**Comment by MountHobbies** [comment]
> All this ^ plus even back on stable 3.4, I'm getting intermittent freeze-frames where the controls and audio still work, but the screen is stuck on a frame until I hit the Steam button once or twice to get the stream to refresh... and audio drops out quite consistently after 5-30 minutes... AND it seems to be impossible to close the game stream from the Deck; it just hangs on a black screen -- but I'm pretty sure the game is actually closed on the host PC.

Turn off hardware decoding and see if that fixes it (this used to be the workaround for a long time for similar issues).

**Comment by kpervin** [comment]
> > All this ^ plus even back on stable 3.4, I'm getting intermittent freeze-frames where the controls and audio still work, but the screen is stuck on a frame until I hit the Steam button once or twice to get the stream to refresh... and audio drops out quite consistently after 5-30 minutes... AND it seems to be impossible to close the game stream from the Deck; it just hangs on a black screen -- but I'm pretty sure the game is actually closed on the host PC.
> 
> Turn off hardware decoding and see if that fixes it (this used to be the workaround for a long time for similar issues).

This doesn't fix it for me. Currently my issue is that I can launch a title, show the connecting screen, but then be booted back to the game page with "Connect" showing in the launch game button.

| Item | Value |
|--------|--------|
| OS Name | "SteamOS Holo" |
| OS Codename | holo |
| OS Variant | steamdeck-bc |
| OS Version | 351 |
| OS Build | 20231011.100 | 
| Kernel Version | 61.52-valve3-1-neptune-61 |
| Steam Deck Controller FW Build Date | Thu Sep 7 3:47 PM UTC-04:00 |
| BIOS Version | F7A0118 |
| Dock Firmware Version | 0.13.15.120 |

**Comment by MountHobbies** [comment]
> > > All this ^ plus even back on stable 3.4, I'm getting intermittent freeze-frames where the controls and audio still work, but the screen is stuck on a frame until I hit the Steam button once or twice to get the stream to refresh... and audio drops out quite consistently after 5-30 minutes... AND it seems to be impossible to close the game stream from the Deck; it just hangs on a black screen -- but I'm pretty sure the game is actually closed on the host PC.
> > 
> > Turn off hardware decoding and see if that fixes it (this used to be the workaround for a long time for similar issues).
> 
> This doesn't fix it for me. Currently my issue is that I can launch a title, show the connecting screen, but then be booted back to the game page with "Connect" showing in the launch game button.
> 
> | Item | Value |
> |--------|--------|
> | OS Name | "SteamOS Holo" |
> | OS Codename | holo |
> | OS Variant | steamdeck-bc |
> | OS Version | 351 |
> | OS Build | 20231011.100 | 
> | Kernel Version | 61.52-valve3-1-neptune-61 |
> | Steam Deck Controller FW Build Date | Thu Sep 7 3:47 PM UTC-04:00 |
> | BIOS Version | F7A0118 |
> | Dock Firmware Version | 0.13.15.120 |

Is your deck docked with an Ethernet cable connected?

**Comment by kpervin** [comment]
> > Replying to [#1148 (comment)](https://github.com/ValveSoftware/SteamOS/issues/1148#issuecomment-1783880296)
> 
> Is your deck docked with an Ethernet cable connected?

That it is.

**Comment by MountHobbies** [comment]
> > > Replying to [#1148 (comment)](https://github.com/ValveSoftware/SteamOS/issues/1148#issuecomment-1783880296)
> > 
> > Is your deck docked with an Ethernet cable connected?
> 
> That it is.


I'm guessing you also have an Ethernet cable on your dock.

Workaround until Volvo plz fix;
Undock, turn off wifi and wait a minute, redock.

You can also turn off either "Steam wired connection" or "Wired connection 1" , then wifi, then wait and minute and re- enable the wires connection

**Comment by Schiffmeister13** [comment]
> > > > Replying to [#1148 (comment)](https://github.com/ValveSoftware/SteamOS/issues/1148#issuecomment-1783880296)
> > > 
> > > 
> > > Is your deck docked with an Ethernet cable connected?
> > 
> > 
> > That it is.
> 
> Workaround until Volvo plz fix; Undock, turn off wifi and wait a minute, redock.
> 
> You can also turn off either "Steam wired connection" or "Wired connection 1" , then wifi, then wait and minute and re- enable the wired connection
> 
> Both do the same thing but the second method is more lazy
> 
> For both you'll probably have to try to launch a remote session a few extra times to connect before steam realizes: " oh new IP address"

Thank you so much. I had the same issue but your workaround helped to solve it for the momemt. Hope there will be a fix in the long run.

**Comment by symulation** [comment]
I am experiencing a version of this problem. Slightly different though, as follows...

Steam Deck restarts on any attempted remote play connection. Previous to whatever update came through about two weeks ago it worked (almost) flawlessly when connected to via a Steam Link box. Since the update to some subversion of 3.5, any attempted remote play connection restarts the Steam Deck. This has been tested via a Steam Link box, the Steam Link app on my phone, and with another computer running steam.

These connections are all via the local network and I’ve rerun all the network cabling fidelity tests and everything passes. These tests include the network connectivity tests available through the Steam Link. Again, this setup was previously working really well.

Various alternative remote play settings, as reported in the community pages, have been attempted. All have failed.

Switching to the beta channel doesn’t seem to make a difference. Swapping to Preview 3.5.11 didn't help either UNTIL...

I managed to get remote play working again briefly last night. This involved unplugging the ethernet cable from the Steam Dock and establishing a remote play connection to the deck through wifi only. Once this connection was closed I was then able establish a remote play connection to the deck when the cable was plugged back into the dock.

I was only able to get this to work via the Steam Link App on my phone. It would not work through the Steam Link Box. I did not test it from the local computer.

This fix did not survive restarts of the deck, although I was able to repeatedly able to replicate the connection with the Steam Link App on my phone.

**Comment by Schiffmeister13** [comment]
> I am experiencing a version of this problem. Slightly different though, as follows...
> 
> Steam Deck restarts on any attempted remote play connection. Previous to whatever update came through about two weeks ago it worked (almost) flawlessly when connected to via a Steam Link box. Since the update to some subversion of 3.5, any attempted remote play connection restarts the Steam Deck. This has been tested via a Steam Link box, the Steam Link app on my phone, and with another computer running steam.
> 
> These connections are all via the local network and I’ve rerun all the network cabling fidelity tests and everything passes. These tests include the network connectivity tests available through the Steam Link. Again, this setup was previously working really well.
> 
> Various alternative remote play settings, as reported in the community pages, have been attempted. All have failed.
> 
> Switching to the beta channel doesn’t seem to make a difference. Swapping to Preview 3.5.11 didn't help either UNTIL...
> 
> I managed to get remote play working again briefly last night. This involved unplugging the ethernet cable from the Steam Dock and establishing a remote play connection to the deck through wifi only (Thanks to @MountHobbies for the hint). Once this connection was closed I was then able to establish a remote play wired connection to the deck when the cable was plugged back into the dock.
> 
> I was only able to get this to work via the Steam Link App on my phone. It would not work through the Steam Link Box. I did not test it from the local computer.
> 
> This fix did not survive restarts of the deck, although I was able to repeatedly able to replicate the connection with the Steam Link App on my phone.

I can relate to this problem somehow. I am using the steam deck via steam dock on my tv as well. However when I am using remote play of the steam deck the image quality is really awfull (very dark and without details)  eventhough I had made all the neccessary configurations on client (Steam deck) and Host ( Gaming PC) for having a high quality stream. Also the lan connection is via CAT 6 cable and more than fast enough and also tested. 
And here comes the conformity to your problem: When I disconnect the ethernet cable and play remote just via Wifi it sometimes works with very high picture quality. Not every time but at least more often than via cable where the quality sucks every time. 
I am very sure this is not an issue of my configuration because it worked via steam link app on samsung TV with good image quality regardless if I used cable or Wifi.

**Comment by symulation** [comment]
Gave up on waiting for a fix for this. Reverted back to the 3.1 image. Everything works. No trouble.

Here's how to revert:

Follow the instructions for doing listed at https://help.steampowered.com/en/faqs/view/1B71-EDF2-EB6D-2BB3.

HOWEVER, following this process exactly will lead you to reinstall a very recent version and maybe that's not what you want. For example, maybe you don't want a fresh install of 3.5.7 and want something earlier.  If so then instead of clicking on the link in Step 1 got to this url instead: [https://steamdeck-images.steamos.cloud/recovery/](https://steamdeck-images.steamos.cloud/recovery/) (This is the location where the file that Step 1 downloads by default is stored but it also holds older versions as well). From the web page that you are presented with choose a file with a creation date close to what you are looking for. I chose the "recovery-4" file thinking that it might hold 3.4. It doesn't. It set me up with 3.1 instead. Which is fine because it works for me. Your mileage may vary. (Would be nice if the file names gave some hint of what they contained.) HINT: unzip the image file to the point where the file name ends in ".img" otherwise the etcher utility will hang indefinitely.

**Comment by NoSadBeHappy** [comment]
I believe I have a version of this issue as well. When streaming from one steam deck to another, it works fine, but when I also stream to a Windows PC, the steam de k freezes but the Windows PC works fine. All local connections, and everything is on wifi. Haven't tried reverting back to a previous version yet.

**Comment by MountHobbies** [comment]
> I believe I have a version of this issue as well. When streaming from one steam deck to another, it works fine, but when I also stream to a Windows PC, the steam de k freezes but the Windows PC works fine. All local connections, and everything is on wifi. Haven't tried reverting back to a previous version yet.

Try Disabling hardware decoding on the client deck via 'enable advanced client options' setting

**Comment by G3NSVRV** [comment]
To me, it worked after running:
- `sudo steamos-readonly disable`
- `sudo pacman-key --init`
- `pacman-key --populate`
- `sudo pacman -Syu`

After a quick restart, everything is working perfectly on GameMode (remote play)

**Comment by NoSadBeHappy** [comment]
I forgot to respond to this. @MountHobbies your tip worked. Disabling hardware decoding fixed the issue.

**Comment by innateessence** [comment]
Tried to play Remote Play with a friend on both my devices and we tried 10 times to no avail.
After some troubleshooting, the closest we got was the game opening, seeing the remote play screen, and then the game just dying. on the Host's end, the Host never even saw the other player join from their Remote Play interface.

My 2 Devices' info Below.

Windows 10 - Fresh Installed 7 days ago at most
- OS Name:                   Microsoft Windows 10 Pro
- OS Version:                10.0.19045 N/A Build 19045
- Steam Beta Branch:  Stable Client
- Steam Version:  1705108172
- Steam Client Build Date:  Fri, Jan 12 4:54 PM UTC -08:00
- Steam Web Build Date:  Fri, Jan 12 9:02 AM UTC -08:00
- Steam API Version:  SteamClient021

Steam Deck OLED
- SteamOS Holo 3.5.7 build 20231122.1
- Kernal Version 6.1.52-valve9-1-neptune-61
- Steam Version 1705108172
- Steam API Version SteamClient021

My Friend was using a SteamDeck as well, Haven't verified, but he was very likely on the same version as my Steam Deck.
His is not an OLED model

**Comment by MattiaTraverso** [comment]
Bug still occurs in 3.5.7.

Steam Deck OLED

    SteamOS Holo 3.5.7 build 20231122.1
    Kernal Version 6.1.52-valve9-1-neptune-61
    Steam Version 1708985249
    Steam API Version SteamClient021

Windows 11 

    OS Name: Windows 11 Home
    OS Version: 23H2
    OS Build: 22631.3155

    Steam Beta Branch:  Stable Client
   Steam Version:  1708985249
   Steam Client Build Date:  Mon, Feb 26 4:44 PM UTC -08:00
   Steam Web Build Date:  Mon, Feb 26 9:21 PM UTC -08:00
   Steam API Version:  SteamClient021

    GPU: NVIDIA GeForce RTX 4070
    Driver Version: 31.0.15.5161
    DirectX Driver Version: 31.0.15.5161
    Driver Date: 2 15 2024

**Comment by MattiaTraverso** [comment]
Update:

When using **remote play from Desktop Mode on the Steam Deck**, the issue presents itself differently: 

**I don't get the loading screen anymore**, and **the stream seems to work** for some time, but it **then freezes on a frame** and never updates the video again.

Note that **if I go to the desktop on my Windows PC** while the game is running (Windows + D), **the stream deck streams my desktop PERFECTLY**, indicating that this is **not a network issue**.

Something is clearly off with video streaming on the Deck.

**Comment by MattiaTraverso** [comment]
UPDATE - **Valve fixed it**: https://store.steampowered.com/news/app/1675200/view/4124805233776542002

Works for me :)

**Comment by kisak-valve** [comment]
Closing per the last comment.

**Comment by weczi** [comment]
3.5++ 
stream working for screen but none of the buttons works on game mode and desktop mode

**Comment by Vexthecollector** [comment]
Streaming to my Steamdeck (Steamdeck is running the game) seems to still be an issue:
SteamOS Holo, version 3.5.19, build 20240422.1
bios F7G0107
I get audio, but I don't get any video to actually see the game itself (This is in gaming mode).
Hardware acceleration enabled/disabled makes no difference.

**Comment by G3NSVRV** [comment]
@Vexthecollector try this

> To me, it worked after running:
> 
> - `sudo steamos-readonly disable`
> 
> - `sudo pacman-key --init`
> 
> - `pacman-key --populate`
> 
> - `sudo pacman -Syu`
> 
> 
> 
> After a quick restart, everything is working perfectly on GameMode (remote play)
> 
> 
> 
> _The mouse is weird tho, it has an absurdly high acceleration on DooM Eternal_
> 
> 
> 
> ## Env
> 
> - SteamOS Holo 3.5.7, build 20231122.1
> 
> - Kernel 6.1.52-valve14-1-neptune-61

**Comment by Vexthecollector** [comment]
> @Vexthecollector try this
> 
> [#1148 (comment)](https://github.com/ValveSoftware/SteamOS/issues/1148#issuecomment-1894816472)

That does not fix it for me.
