### ISSUE TITLE
External display game mode performance issues

### ISSUE THREAD

**Issue by kasseg** [ValveSoftware/SteamOS#1219]
#### Your system information

* Steam client version:
* SteamOS version: 3.5.5 / 3.6
* Opted into Steam client beta?: [Yes/No] 
* Opted into SteamOS beta?: Tried both 
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
I have huge performance degradation when Steam Deck is connected to external display in game mode and display's resolution is above 1080p. Game mode shell is VERY luggy in 4k now, its around 15fps only with a lot of freezes.

It also impact on the game performance.

The second bug is the new fps/hz limiter is broke deck's performance when enabled on external display.
Check this video: 
https://www.youtube.com/watch?v=F3fa135hcEg

When limiter is enabled, game will only runs in 20-25fps. When I clicked on the steam menus buttons - it become 40fps, so it runs normal while menus shown. After that I rotate camera in game a little and it become 20-25fps again.
But if I disable limiter, the game will run smooth with 40-45 fps.

These issues doesnt exists on 3.5/3.6 builds, that was BEFORE 3.5.5 release builds.
Also desktop mode seems to work well too.

#### Steps for reproducing this issue:

1. Connect steam deck to external display
2. Set resolution to 1440p/4k
3. Game mode is very luggy

**Comment by kasseg** [comment]
Some more info:

Looks like it have 30fps cap, because it will never go above 30 anywhere in game mode (library, any game etc). It also works with kind of x0.5 coefficient with limiter (still caped to 30fps)
For example, when I choose 120fps/hz in limiter, it caped 30fps.
60fps/120hz limit is also caped to 30fps.
40fps/120hz limit will be caped to 20fps.
30 -> 15
24 -> 12
20 -> 10.

It is VERY annoying regression, because now I have to choose 1080p120hz and can’t use 4k anymore. But just before 3.5 releases (oled merged to branches) it was OK.

It also works without any issues in 4k120hz in desktop mode.

Returning to legacy limiter and any other limit/unlimit combinations doesn’t help

**Comment by Joshua-Ashton** [comment]
Hello, are you able to tell me if you had a scaling filter such as FSR/NIS enabled when testing this?

Thanks!

**Comment by aprusik** [comment]
Hello,

I ran into the same issue today. I was able to get some games to run at 4k60hz by manually setting the GPU clock to 1600. The steam menus would also report above 30fps after this, but they were still super choppy and laggy. No matter what I did I still couldn't get anything to go above 60hz unless I turned the resolution down to 1080p. 

My completely uninformed guess says it has something to do with the way they turned the power curves for the OLED and the new APU. since the steam deck doesn't seem to want to devote a lot of power to run the menus, which makes sense but it's needed at 4k.

**Comment by KrisCris** [comment]
When connecting my OLED deck to my 4k60hz display, it's locked to 15fps :/

**Comment by Joshua-Ashton** [comment]
@KrisCris Does the problem happen on Preview channel?

**Comment by KrisCris** [comment]
@Joshua-Ashton Sorry, after testing I realized that my issue was caused by NIS/FSR. Turning these off fixed it.

**Comment by kasseg** [comment]
Any updates on this?
@Joshua-Ashton 
So does you replicate this issue?

**Comment by kasseg** [comment]
It feels very uncomfortable and unfair that my deck can’t do 4k now. Because it was able to

**Comment by Joshua-Ashton** [comment]
It should be fixed in Preview like I mentioned above. If it isn't, let me know.

**Comment by kasseg** [comment]
> It should be fixed in Preview like I mentioned above. If it isn't, let me know.

Im on some of the january builds, not the latest though. And the problem is still exists. I will try with the latest soon. But I can't notice anything related to this problem in the release notes. But i will test

**Comment by kasseg** [comment]
Just tested with latest. It’s bugged. Game mode steam seems like caped to 40fps in 4k120 resolution. It’s very laggy and slow. Maybe it is not cap but performance limit, I don’t know.

in games it goes above, but fps/refresh limit seems to be bugged as well. I tried new (combined) and old. It’s weird. No fsr/nis.

It was much better just few months before. Desktop mode seems to work well.

I think it is gamescope bug.

Another weird thing that old fps limit options are for 4k144 resolution. It is 144/72/36. New one is 120/60/40/30/24.

**Comment by kasseg** [comment]
Is there a way to install different version of gamescope?

**Comment by matheusfaustino** [comment]
Just tested today, using preview channel, and somewhat seems cap at 30fps (the tv is 60), at least, it is not 15 anymore. I changed the gpu clock and it did not affect anything, it was hard locked at 30fps using FSR, other methods were fine. 

Build is 20240212.1 and kernel is 6.1.52-valve16-1-neptune-61.

**Comment by waspennator** [comment]
@Joshua-Ashton Still seem to see people reporting the problem is still here on the bug report thread on the steam deck community hub.

**Comment by ChrisBln2302** [comment]
I can confirm that the issue still exists. With 3.5.17 fps still going down from 60 to 30 when using FSR and the deck is connected to an external display.

**Comment by Ruffnik** [comment]
Happens on 3.5.17 as well on my 4k TV, framerate drops down to 15. I don't observe such a drop on my FHD projector.

**Comment by polyjitter** [comment]
Still happening, 4K @ 60hz (manually set in Steam settings) w/ FSR enabled caps framerate in game to 30. I'm assuming wontfix with how long this has been open with no resonse

**Comment by Joshua-Ashton** [comment]
@polyjitter FSR'ing from 720p up to 4K is expensive. Realistically I should add a limit or something to 1080p then have the HW scale it up from there.

**Comment by polyjitter** [comment]
> @polyjitter FSR'ing from 720p up to 4K is expensive. Realistically I should add a limit or something to 1080p then have the HW scale it up from there.

I do understand that it's expensive, but also this is experienced attempt to go from 1080 -> 4K. It kinda makes FSR pointless because I get higher framerates at native 4K anyways lol

**Comment by francois-pasquier** [comment]
> @polyjitter FSR'ing from 720p up to 4K is expensive. Realistically I should add a limit or something to 1080p then have the HW scale it up from there.

Is it the cause of 4k120 being stuck at 30fps on gaming mode though?

Anything we can do to fix it?

**Comment by Joshua-Ashton** [comment]
@francois-pasquier Even without FSR? I do not see that behaviour here on my display. Can you give details as to what your setup is?

**Comment by Joshua-Ashton** [comment]
Can you also see if SteamOS Main fixes the problem?

**Comment by francois-pasquier** [comment]
> @francois-pasquier Even without FSR? I do not see that behaviour here on my display. Can you give details as to what your setup is?
![IMG_3980](https://github.com/ValveSoftware/SteamOS/assets/19970734/fb02fec4-fd65-4934-b220-2dc326af5d55)

Yes, 4k@120 is locked on 30fps max without FSR.
Enabling FSR lowers it to 20fps.

basically 4k@60 works fine but as soon as I enable a higher refresh rate, everything is super slow including launching games and menus

I am on Beta channel, version 3.5.17 20240228.2

**Comment by Hatsune-Cthulhu** [comment]
Also experiencing this, very annoying bug since it's causing me to get lower FPS when using 1080p+FSR than I do just running the game at native 4K

**Comment by lbibass** [comment]
I am having this problem when running steamOS Preview, Main, and Beta. Only the SteamOS Stable branch fixes this problem. I am running an OLED model. 

This half-rate UI is a problem when both connected to a monitor with the official dock, and on the integrated display.

**Comment by Kisamegr** [comment]
Have the same issue with steam deck OLED in latest BETA channel and 3rd party dock :/

**Comment by BluePhoenix** [comment]
Still experiencing this, in my case, when I really want FSR on the external display, I noticed that manually setting the clock speed to 1500 MHz it renders at 60 FPS. 

Otherwise it would go to 15 fps and use maybe 600 MHz gpu clock speed. 

Maybe the logic that determines clock speed needs to be adjusted for this scenario (4k external display) ?

Can anyone else confirm that manually setting GPU clock speed higher renders at higher fps?
(This is more of a workaround than a fix though, it would be preferable to leave clock at auto setting)

**Comment by Joshua-Ashton** [comment]
This should be fixed by the time we start actually pushing on SteamOS 3.7 as new kernel stuff combined with the gamescope layer allows us to inline FSR work with the game in certain scenarios.

**Comment by BluePhoenix** [comment]
That's great news. Looking forward to it and thanks for the update @Joshua-Ashton !

**Comment by Omarock92** [comment]
I have this issue on my OLED deck (stable release) connected to a TV through HDMI 2.1 at 4k@120hz mode. TV shows correct 4k@120hz but everything from the OS to games are stuck at 40fps. 
4k@60hz work fine, and everything below (like 1440p@120hz, etc...)

Glad to hear it's being fixed.

**Comment by Omarock92** [comment]
> I have this issue on my OLED deck (stable release) connected to a TV through HDMI 2.1 at 4k@120hz mode. TV shows correct 4k@120hz output but everything from the OS to games are stuck at 40fps. 4k@60hz work fine, and everything below (like 1440p@120hz, etc...)
> 
> Glad to hear it's being fixed.

This is still an issue in 3.7.8

**Comment by waspennator** [comment]
> This should be fixed by the time we start actually pushing on SteamOS 3.7 as new kernel stuff combined with the gamescope layer allows us to inline FSR work with the game in certain scenarios.

Any update on this being fixed?

**Comment by lmossman** [comment]
@misyltoad is there any progress on getting this 4k fps issue fixed? I finally got an hdmi 2.1 dock and I was excited to start streaming at 4k 120fps since I read that was possible, but now I've found this thread and learned that it is still in a broke state.

**Comment by Tianesus** [comment]
Hiya, I've been encountering a very similar issue, I'll try to describe it as best as I can:

By base it seems like the Deck automatically assigns the system the resolution of 3840x2160@60

Manually setting it to 3840x2160@120 has the menu actually move at 40fps, and setting it to 3840x2160@100 has the menu move at 33fps. In both of those cases the target fps is instead divided by 3

Additionally, after changing the display resolution to one of these broken 4k ones, leaving the settings panel and returning to it has the resolution field be populated with the PREVIOUSLY assigned resolution, instead of the currently assigned one (So for example I would go from device-assigned resolution to 3840x2160@120, exit the settings menu, open it again, see 3840x2160@60 in the "Resolution" field despite that not being the case)

Yet another unintended interaction that's related with this is, if I had gone from 3840x2160@60 to 3840x2160@120, refreshed the settings menu, set the resolution once again to 3840x2160@120, the whole display would brighten up until I set it to a different resolution.

This was tested on an LCD Steam Deck connected to an LG QNED 50QNED85T3A via HDMI 2.1 (I've triple checked to make sure the dock is truly 4k120hz capable on another machine) SteamOS version 3.7.19, [this](https://store.steampowered.com/news/app/1675200/view/500591142199362242?l=english) being the last update I've had on the deck.

Please let me know if you need any more details, I'll try to get back to you asap

**Comment by Hatsune-Cthulhu** [comment]
This is never getting fixed is it? 😭

**Comment by StrikeNP** [comment]
I also have this issue and spent a _lot_ of time messing with it. Some form of this issue appears to still be present. Related reddit post: https://www.reddit.com/r/SteamDeck/comments/1qi9kpt/fps_issues_when_on_external_monitor_set_the/

**Comment by Sehyn** [comment]
After more than three years, this issue still does not appear to have been addressed.

While the workaround functions in Desktop mode, it is not practical for regular use. Additionally, the issue persists entirely in Gaming mode, where it does not work at all.

---

**Observed behavior:**

* The UI appears to be capped at 40 FPS when navigating the library.
* In-game performance seems limited to around 30 FPS.

**Configuration details:**

* FSR/NIS disabled
* Certified HDMI 2.1 cable
* Certified dock in use

Despite all monitoring tools reporting 120 FPS (Gamescope overlay, TV refresh rate, and in-game FPS counters), the actual visual output looks closer to ~30 FPS.

This suggests the issue may originate from Gamescope.

---

**Troubleshooting performed:**

* Tested across all update channels: Stable, Beta, and Preview
* Issue persists in all cases

---

Please allow us to use our devices to their full potential, or if the device is not capable don't allow us to set a resolution and an refresh rate that can't be used.
@misyltoad
