### ISSUE TITLE
Overlay Menus Don't appear during Remote Play

### ISSUE THREAD

**Issue by tjaRoxasXIII** [ValveSoftware/SteamOS#1351]
* Steam client version: 
* SteamOS version: 3.5.7
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No 
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
When streaming games over Remote Play from my PC, the 'Steam' and 'Quick Access' buttons don't appear to initiate the appropriate behavior.   
For the 'Steam' button, the noise is played as if the menu has opened, but nothing appears and the game will continue running without interruption.
For the 'Quick Access' button, the noise is played and the menu appears to become active in the background as navigation sounds play and the controls are no longer being sent into the game.  Pressing the button appears to then close the menu and the game resumes as normal.  This issue has dated back for the last several OS Versions for me.

#### Steps for reproducing this issue:

1. Open a game on a Remote System from the Steam Deck's launcher
2. Once the game has launched, press either the 'Steam' or 'Quick Access' button to initiate the above described behavior.

**Comment by MisterFunkee** [comment]
Copy that. It’s def hardware encoding on SD turned off causing that. 

And 2nd post is also right. The hardware encoding totally messes up screen brightness and also HDR if available.

**Comment by luisfagundes94** [comment]
I'm having the same issue. Overlay won't show if hardware encoding is disabled.

**Comment by Milksheyke** [comment]
Same

**Comment by mgarod** [comment]
Same issue. I have turned off hardware decoding and can no longer view the steam overlay when streaming from PC to the deck.

**Comment by luisfagundes94** [comment]
I've fixed this issue by disabling the performance overlay before launching a game.

**Comment by Technoodle** [comment]
Issue still exists on v3.7.13 & the v3.7.14 beta.
Disabled performance overlay, but it didn't do anything for me.

**Comment by FearlessSpiff** [comment]
Is there a workaround? I tried SW/HW decoding, enabling/disabling overlay, but nothing works. Thanks!

**Comment by crescentduchess** [comment]
This issue is still occuring. With hardware decoding disabled I cannot open overlay, open keyboard, create clips or use any other Game Recording shortcuts. With hardware decoding enabled, my games stutter and lag so much they are unplayable

**Comment by jgaver08** [comment]
This issue has popped back up for me again in 3.8.10.  It had been working on 3.7.25.

**Comment by LessLuck** [comment]
Same here

#### Your system information

* Steam client version: 
* SteamOS version: 3.8.13
* Opted into Steam client beta?: [Yes/No] 
* Opted into SteamOS beta?: [Yes/No] No
* Have you checked for updates in Settings > System?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Used remote play feature (streaming from my PC to steam deck)
When I try to use Quick Access overlay - it shows up for a second and then disappears. It is possible to control it while it's invisible, when I use touch screen I can hear sounds of performance window buttons being pressed. It is also closable when I press either Quick Access button again, or B.
When I am using the STEAM overlay - it does show up, but when I use buttons like "quit game" - the confirmation window appears for a second and then disappear, even tho it is also still interactive - I cannot see what actions I am performing on it.
Absolutely the same scenario goes for the "Hold power button" window

#### Steps for reproducing this issue:

1. Open "Quick Access", "Hold power button menu", "Quit game confirmation screen"
2. None of the screens above are visible for more than a second
3. Screens are still interactable, and can sometimes be seen when opening up STEAM overlay, but disappear when you close it

**Comment by ProgHunter** [comment]
Same problem with SteamOS on the Steam Machine.

**Comment by ghost** [comment]
Hello,
Same issue with steam deck in latest stable version 3.8.14 to a windows 11 host.

**Comment by vladradamus** [comment]
Same issue with 3.8. Quick access menu is not visible when streaming by using Steam's remote play. There are sounds like it's open but nothing is visible.

**Comment by wineTGH** [comment]
Same issue, but hardware encoding enabled on both systems. PC runs fedora 44 and steam deck latest stable update
