### ISSUE TITLE
Sleep issue on Main 3.7, SD wakes by itself again 

### ISSUE THREAD

**Issue by ezzinekaemel** [ValveSoftware/SteamOS#1493]
#### Your system information

* Steam client version: Main Beta 3.7
* SteamOS version: 3.7
* Opted into Steam client beta?: [Yes] 
* Opted into SteamOS beta?: [Yes] 
* Have you checked for updates in Settings > System?: [Yes]

On main beta 3.7, when putting to sleep via button, steamdeck does the sleep animation. Screen black for a second then turns on by itself. Can be reproduced on every game and every time. Issue not available when moving away from main 3.7 

#### Steps for reproducing this issue:

1. Put sd to sleep. Wakes up by itself again. 
2. 
3.

**Comment by philfycasual** [comment]
I've seen this too, notably when docked in desktop mode.

**Comment by sdornan** [comment]
I am having this issue on SteamOS 3.6

**Comment by safijari** [comment]
Seeing the same issue on 3.6 which is now on preview. Using Steam Deck OLED

**Comment by lostgoat** [comment]
If this happens to you again, please go to settings->system and submit a system report.

Then reply here with your steam username or profile link and I can take a look at your logs.

**Comment by sdornan** [comment]
What's sometimes happening now is: 

1. Put it to sleep
2. Wakes up
3. Put it to sleep
4. Stays asleep

I can't confirm that's it's happening every time, but it's definitely happening some of the time. Just submitted a system report. My username is sdornan, same as here.

**Comment by lostgoat** [comment]
Thanks for the system report.

Also, for anyone familiar with a terminal, besides the system report collecting this extra data would also be useful after the system wakes up:
```
cat /sys/power/pm_wakeup_irq
cat /proc/interrupts
```

**Comment by kuhjunge** [comment]
Hello, I have the same issue on Steam OS 3.6 with my OLED SteamDeck. It happens every time I try to put the Steam Deck to sleep while playing "Cassette Beasts". 

Handle: quh91 (system report submitted)

`$ cat /sys/power/pm_wakeup_irq
25`
<details>
  <summary>cat /proc/interrupts</summary>
  
`$ cat /proc/interrupts
            CPU0       CPU1       CPU2       CPU3       CPU4       CPU5       CPU6       CPU7       
   0:         44          0          0          0          0          0          0          0   IO-APIC    2-edge      timer
   1:          0          0          0          0          0          0         53          0   IO-APIC    1-edge      i8042
   4:          0          0          0          0        258          0          0          0   IO-APIC    4-edge      AMDI0010:02
   6:          0          0          0          0          0          0          0          0   IO-APIC    6-edge      AMDI0010:03
   7:          0          0          0          0          0          0        629          0   IO-APIC    7-fasteoi   pinctrl_amd
   8:          0          0          0          0          0          1          0          0   IO-APIC    8-edge      rtc0
   9:          0       3301          0          0          0          0          0          0   IO-APIC    9-fasteoi   acpi
  10:          0          0      17239          0          0          0          0          0   IO-APIC   10-edge      AMDI0010:00
  11:          0          0          0       4926          0          0          0          0   IO-APIC   11-edge      AMDI0010:01
  15:          0          0        190       1704          0          0          0          0   IO-APIC   15-edge      ttyS5
  25:          0          0          0          0          0          0          0          2  PCI-MSI-0000:00:01.2    0-edge      PCIe PME, aerdrv, pcie-dpc
  26:          0          0          0          0          0          0          0          0  PCI-MSI-0000:00:01.3    0-edge      PCIe PME, aerdrv, pcie-dpc
  27:          0          0          0          0          0          0          0          0  PCI-MSI-0000:00:01.4    0-edge      PCIe PME, aerdrv, pcie-dpc
  28:          0          0          0          0          0          0          0          0  PCI-MSI-0000:00:08.1    0-edge      PCIe PME
  29:          0          0          0          0          0          0          0          0  PCI-MSI-0000:00:08.2    0-edge      PCIe PME
  30:          0          0          0          0          0          0          0          0  PCI-MSI-0000:00:08.3    0-edge      PCIe PME
  32:          0          0          0          0          0          0      31792          0  PCI-MSIX-0000:04:00.3    0-edge      xhci_hcd
  33:          0          0          0          0          0          0          0          0  PCI-MSIX-0000:04:00.3    1-edge      xhci_hcd
  34:          0          0          0          0          0          0          0          0  PCI-MSIX-0000:04:00.3    2-edge      xhci_hcd
  35:          0          0          0          0          0          0          0          0  PCI-MSIX-0000:04:00.3    3-edge      xhci_hcd
  36:          0          0          0          0          0          0          0          0  PCI-MSIX-0000:04:00.3    4-edge      xhci_hcd
  37:          0          0          0          0          0          0          0          0  PCI-MSIX-0000:04:00.3    5-edge      xhci_hcd
  38:          0          0          0          0          0          0          0          0  PCI-MSIX-0000:04:00.3    6-edge      xhci_hcd
  39:          0          0          0          0          0          0          0          0  PCI-MSIX-0000:04:00.3    7-edge      xhci_hcd
  41:          0          0          0          0          0          0     154042          0  PCI-MSIX-0000:04:00.4    0-edge      xhci_hcd
  42:          0          0          0          0          0          0          0          0  PCI-MSIX-0000:04:00.4    1-edge      xhci_hcd
  43:          0          0          0          0          0          0          0          0  PCI-MSIX-0000:04:00.4    2-edge      xhci_hcd
  44:          0          0          0          0          0          0          0          0  PCI-MSIX-0000:04:00.4    3-edge      xhci_hcd
  45:          0          0          0          0          0          0          0          0  PCI-MSIX-0000:04:00.4    4-edge      xhci_hcd
  46:          0          0          0          0          0          0          0          0  PCI-MSIX-0000:04:00.4    5-edge      xhci_hcd
  47:          0          0          0          0          0          0          0          0  PCI-MSIX-0000:04:00.4    6-edge      xhci_hcd
  48:          0          0          0          0          0          0          0          0  PCI-MSIX-0000:04:00.4    7-edge      xhci_hcd
  50:          0          0          0         76          0          0          0          0  PCI-MSIX-0000:01:00.0    0-edge      nvme0q0
  51:       2489          0          0          0          0          0          0          0  PCI-MSIX-0000:01:00.0    1-edge      nvme0q1
  52:          0       3233          0          0          0          0          0          0  PCI-MSIX-0000:01:00.0    2-edge      nvme0q2
  53:          0          0       3604          0          0          0          0          0  PCI-MSIX-0000:01:00.0    3-edge      nvme0q3
  54:          0          0          0       2744          0          0          0          0  PCI-MSIX-0000:01:00.0    4-edge      nvme0q4
  55:          0          0          0          0       3251          0          0          0  PCI-MSIX-0000:01:00.0    5-edge      nvme0q5
  56:          0          0          0          0          0       1803          0          0  PCI-MSIX-0000:01:00.0    6-edge      nvme0q6
  57:          0          0          0          0          0          0       3348          0  PCI-MSIX-0000:01:00.0    7-edge      nvme0q7
  58:          0          0          0          0          0          0          0       1758  PCI-MSIX-0000:01:00.0    8-edge      nvme0q8
  59:          0          0          0          0          0          0          0          0  PCI-MSIX-0000:01:00.0    9-edge      nvme0q9
  60:          0          0          0          0          0          0          0          0  PCI-MSIX-0000:01:00.0   10-edge      nvme0q10
  61:          0          0          0          0          0          0          0          0  PCI-MSIX-0000:01:00.0   11-edge      nvme0q11
  62:          0          0          0          0          0          0          0          0  PCI-MSIX-0000:01:00.0   12-edge      nvme0q12
  63:          0          0          0          0          0          0          0          0  PCI-MSIX-0000:01:00.0   13-edge      nvme0q13
  64:          0          0          0          0          0          0          0          0  PCI-MSIX-0000:01:00.0   14-edge      nvme0q14
  65:          0          0          0          0          0          0          0          0  PCI-MSIX-0000:01:00.0   15-edge      nvme0q15
  66:          0          0          0          0          0          0          0          0  PCI-MSIX-0000:01:00.0   16-edge      nvme0q16
  68:      18972          0          0          0          0          0          0        707  PCI-MSI-0000:02:00.0    0-edge      mmc0
  69:          0          0          0          0          0          0        626          0  amd_gpio   84  FTS3528:00
  71:          0          0          0          0          0          0          0          0  PCI-MSIX-0000:04:00.2    0-edge      psp-1
  73:          0          0          0          0          0          0          3          0  amd_gpio   86  nau8821
  74:          0          0          0          0      15141          0          0          0   IO-APIC   27-fasteoi   AudioDSP
  75:          0          0          0          0          0          0        661          0  PCI-MSI-0000:04:00.1    0-edge      snd_hda_intel:card0
  76:      24419          0          0          0          0          0          0          0  PCI-MSI-0000:03:00.0    0-edge      bhi, mhi, mhi, ce0, ce1, ce2, ce3, ce5, ce7, ce8, DP_EXT_IRQ, DP_EXT_IRQ, DP_EXT_IRQ, DP_EXT_IRQ, DP_EXT_IRQ, DP_EXT_IRQ, DP_EXT_IRQ, DP_EXT_IRQ, DP_EXT_IRQ, DP_EXT_IRQ
  77:          0          0          0          0          0     237695          0          0  PCI-MSIX-0000:04:00.0    0-edge      amdgpu
 NMI:        264         10         13         19         17         10         15         10   Non-maskable interrupts
 LOC:     530949     237482     250374     188429     251127     243318     393015     205992   Local timer interrupts
 SPU:          0          0          0          0          0          0          0          0   Spurious interrupts
 PMI:        265         10         13         19         17         10         15         10   Performance monitoring interrupts
 IWI:          1          0          4          2          0       3955          0          0   IRQ work interrupts
 RTR:          0          0          0          0          0          0          0          0   APIC ICR read retries
 RES:       8136      27238      30564       4413       6333      12221      13247      11245   Rescheduling interrupts
 CAL:     332617     355482     372227     225562     305450     292097     319394     307725   Function call interrupts
 TLB:       8800       8835       7542       7760       8323       8340       8999       7581   TLB shootdowns
 TRM:          0          0          0          0          0          0          0          0   Thermal event interrupts
 THR:          0          0          0          0          0          0          0          0   Threshold APIC interrupts
 DFR:          0          0          0          0          0          0          0          0   Deferred Error APIC interrupts
 MCE:          0          0          0          0          0          0          0          0   Machine check exceptions
 MCP:          2          2          2          2          2          2          2          2   Machine check polls
 ERR:          0
 MIS:          0
 PIN:          0          0          0          0          0          0          0          0   Posted-interrupt notification event
 NPI:          0          0          0          0          0          0          0          0   Nested posted-interrupt event
 PIW:          0          0          0          0          0          0          0          0   Posted-interrupt wakeup event
`

</details>

**Comment by lostgoat** [comment]
@kuhjunge the device waking up your deck is the SSD. Are you using the original SSD or an aftermarket SSD?

**Comment by kuhjunge** [comment]
I have a aftermarket SSD (WD PC SN740 NVMe SSD 2TB).

**Comment by sdornan** [comment]
I have the same SSD.

**Comment by dangerousdonut** [comment]
I've been seeing this in 3.6.3 as well. Press the button, sleep animation, then back to being on like nothing happens. After one or two more tries it usually goes to sleep.

**Comment by austin-ek** [comment]
I have this same issue with the SN740 2TB on 3.6 Preview

**Comment by lostgoat** [comment]
There is a potential fix to prevent these SSDs from preventing the deck from going to sleep in the 6.5.0-valve7 kernel. I’ll update this thread once that kernel is available in a SteamOS image so you can test it.

**Comment by jbbandos** [comment]
Same issue on 3.6.x, but my SSD is a Sabrent Rocket Q4 2TB.

**Comment by lostgoat** [comment]
The kernel with the potential fix is now available in the "Main" OS update channel. Would be good to know if it addresses the sleep bug with your SSDs.

I would recommend opting from Main back to Beta or Stable after you run your tests, as Main can often have a lot of unexpected bugs. It is the nightly development build of SteamOS.

You can confirm you have the right kernel by running this command and checking that the version says `valve7`:
```
(deck@steamdeck ~)$ uname -a
Linux steamdeck 6.5.0-valve7-1-neptune-65-gbb001cd639ba #1 SMP PREEMPT_DYNAMIC Thu, 23 May 2024 19:56:36 +0000 x86_64 GNU/Linux
```

If you don't know how to install the Main OS beta, don't worry this fix will be coming to Preview soon.

**Comment by jbbandos** [comment]
I've just installed main, and my first findings are that both for gaming mode and desktop mode suspend seems to work, even when playing a game, but resume does a reboot, back to the "checking the installation" boot screen, followed by the boot video.

$ uname -a
Linux steamdeck 6.5.0-valve7-1-neptune-65-gbb001cd639ba #1 SMP PREEMPT_DYNAMIC Thu, 23 May 2024 19:56:36 +0000 x86_64 GNU/Linux

$ sudo smartctl -a /dev/nvme0
smartctl 7.4 2023-08-01 r5530 [x86_64-linux-6.5.0-valve7-1-neptune-65-gbb001cd639ba] (local build)
Copyright (C) 2002-23, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Number:                       Sabrent Rocket Q4
Serial Number:                      xxxxxxxxxxxxxx
Firmware Version:                   RKT23Q.1
PCI Vendor/Subsystem ID:            0x1987
IEEE OUI Identifier:                0x6479a7
Controller ID:                      0
NVMe Version:                       1.4
Number of Namespaces:               1
Namespace 1 Size/Capacity:          2,000,398,934,016 [2.00 TB]
Namespace 1 Formatted LBA Size:     512
Namespace 1 IEEE EUI-64:            6479a7 7a30c01c07
Local Time is:                      Thu May 30 18:27:26 2024 CEST
Firmware Updates (0x12):            1 Slot, no Reset required
Optional Admin Commands (0x0017):   Security Format Frmw_DL Self_Test
Optional NVM Commands (0x0056):     Wr_Unc DS_Mngmt Sav/Sel_Feat Timestmp
Log Page Attributes (0x0e):         Cmd_Eff_Lg Ext_Get_Lg Telmtry_Lg
Maximum Data Transfer Size:         64 Pages
Warning  Comp. Temp. Threshold:     83 Celsius
Critical Comp. Temp. Threshold:     85 Celsius
Namespace 1 Features (0x08):        No_ID_Reuse

**Comment by lostgoat** [comment]
@jbbandos can you submit a system report after you see the resume/rebooting bug? You can do that from Settings->System->scroll to bottom of page. Then I can pull the data if you send me your steam account name.

**Comment by jbbandos** [comment]
@lostgoat Done. And my steam account name is jbbandos also.

**Comment by jbbandos** [comment]
@lostgoat New report submitted. I've uninstalled decky,  rebooted, then switched to offline mode and suspended. Still restarted when resuming.

**Comment by austin-ek** [comment]
I installed the main branch on my SN 470 2TB. Zero sleep issues now, works perfectly, just like 3.5

I am not experiencing any resume issues like @jbbandos is describing. 

I tested in desktop & game mode, and with a game open (Starfield, which is probably the heaviest game I own).

**Comment by dangerousdonut** [comment]
For reference, I'm having this issue on a stock SSD. Haven't installed the update from main yet though.

**Comment by lostgoat** [comment]
@jbbandos I think the resume from sleep issue is something separate. I've seen another report of someone with the same symptoms that was running the beta branch.

I've created a separate issue for that problem. Can I trouble you to trigger the bug again and check if you have any kdump files in the directories I mentioned in https://github.com/ValveSoftware/SteamOS/issues/1536.

**Comment by austin-ek** [comment]
Just installed the latest Preview 3.6.4, works great!

**Comment by danykaufman** [comment]
Hi.
Still experiencing the issue on 3.6.4 and 3.6.5
SD oled + SN740 2T

**Comment by jbbandos** [comment]
Resume from sleep is now fixed, but I still have the sleep/wake issue on 3.6.5. It isn't everywhere - on the games I tested, it happens only in Fallout 4 while playing a game. Loading a game or on the main menu it suspends and stays suspended until I wake it.
`$ uname -a`
`Linux steamdeck 6.5.0-valve11-1-neptune-65-gfc341bb964a8 #1 SMP PREEMPT_DYNAMIC Wed, 12 Jun 2024 02:34:04 +0000 x86_64 GNU/Linux`

**Comment by lostgoat** [comment]
Thanks for the issue report and testing to confirm the issue is resolved.

**Comment by jbbandos** [comment]
@lostgoat I hate to be that guy, but this isn't fixed. For me the deck keeps waking up immediately when I put it to sleep in some of the games. No Man's Sky will wake up immediately everywhere, Fallout 4 only inside the game itself (not if loading or on the main menu)
I'm now on:
`$ uname -a`
`Linux steamdeck 6.5.0-valve12-1-neptune-65-g1889664e19fc #1 SMP PREEMPT_DYNAMIC Fri, 21 Jun 2024 00:07:43 +0000 x86_64 GNU/Linux
`

**Comment by lostgoat** [comment]
@jbbandos please open a new issue and submit a system report after you trigger the bug.
