### ISSUE TITLE
[SteamDeck] Development mode not connecting

### ISSUE THREAD

**Issue by randomnumgen1** [ValveSoftware/SteamOS#2258]
#### Your system information

* Steam client version: 1767142807
* SteamOS version: 3.7.19
* Opted into Steam client beta?: [Yes/No] 
* Opted into SteamOS beta?: [Yes/No] 
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
SteamDeck was expected to connect to the pc devkit app.
SteamDeck did not connect and didn't display anything happening when clicking pair.
pc devkit app showed error: 

#### Steps for reproducing this issue:
1.   start devkit client on PC
2.  Turn on steam deck
3.  Enable Developer mode
4.  steamdeck > development host pairing > pair new host
5. pc > steamos devkitclient > register
6. pc > steamos devkitclient error "devkit approve-ssh-key: please put the steam client in pairing mode"

Steam Deck system reports steamid: 76561198261845243

I have also tried switching between stable and beta and also factory reset through steam and also reinstalling steamos through USB stick ( https://help.steampowered.com/en/faqs/view/65B4-2AA3-5F37-4227 )

**Comment by IoriBranford** [comment]
Granted I am using another OS but I would guess the bug is in the devkit service or in Steam. https://gitlab.steamos.cloud/devkit/steamos-devkit-service

Client:
```
Looking for machine with service name: cachyos-deck
Machine IP: 192.168.1.30
Registering with devkit at ip: 192.168.1.30
'cachyos-deck': register command failed
Traceback (most recent call last):
  File "/home/kevin/.shiv/devkit-gui-cp312.pyz_1850796350ab4ecc6c01bb08b68ffba4ef0829caa8e30bd1d1a423d15f9311f6/site-packages/devkit_client/gui2/gui2.py", line 891, in draw
    self._result = self.task_future.result()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kevin/.pyenv/versions/3.12.12/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/kevin/.pyenv/versions/3.12.12/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
Exception: devkit approve-ssh-key: please put the Steam client in pairing mode: Settings -> Developer -> Pair new host
```

Service: `sudo systemctl status steamos-devkit-service.service`
```
Jan 04 13:33:02 cachyos-deck python[2134]: Filename key written to: /tmp/devkit-1hnp9ttvb
Jan 04 13:33:02 cachyos-deck python[3659]: /usr/share/steamos-devkit/hooks/approve-ssh-key:Sending pairing request to Steam
Jan 04 13:33:03 cachyos-deck python[2134]: 192.168.1.105 - - [04/Jan/2026 13:33:03] "POST /register HTTP/1.1" 403 -
Jan 04 13:33:39 cachyos-deck python[2134]: register request from 192.168.1.105
Jan 04 13:33:39 cachyos-deck python[2134]: Key is valid base64, writing to temp file index: 380
Jan 04 13:33:39 cachyos-deck python[2134]: Found name ending index 380
Jan 04 13:33:39 cachyos-deck python[2134]: Found name ending at index 409
Jan 04 13:33:39 cachyos-deck python[2134]: Filename key written to: /tmp/devkit-1mrjntdw0
Jan 04 13:33:39 cachyos-deck python[4183]: /usr/share/steamos-devkit/hooks/approve-ssh-key:Sending pairing request to Steam
Jan 04 13:33:40 cachyos-deck python[2134]: 192.168.1.105 - - [04/Jan/2026 13:33:40] "POST /register HTTP/1.1" 403 -
```

**Comment by LyffLyff** [comment]
Got the same Issue, any ways you fixed it?

**Comment by Flobu** [comment]
it seems to be introduced between SteamOS 3.7.17 and 3.7.19

we have 2 steamdecks here
one with 3.7.17 installed still where it works fine
and another one with 3.7.19 where i get the same error

edit:
I downgraded the 3.7.19 one to 3.7.17 now via 
> sudo steamos-atomupd-client --update-from-url https://steamdeck-images.steamos.cloud/steamdeck/20251027.1/steamdeck-20251027.1-3.7.17.raucb

they are now both on the same steam os version and steam version the only difference is the BIOS Version and its still not working  :(
different BIOS seems to be because one is LCD variant and the other one is OLED
F7A0131 (works) LCD
F7G0112 (doesn't work) OLED

**Comment by randomnumgen1** [comment]
@Flobu could it be that its only working on your LCD due to it being already registered with the devkit client?

**Comment by Flobu** [comment]
sure could be that its in a state where it accepts new pairing already, i was able to pair other pcs that had no pairing before with the LCD one
but none of them want to pair with the new OLED one (maybe it was wrongly setup?) steam link pairing and playing works fine on it

are you using a LCD or OLED model?

**Comment by randomnumgen1** [comment]
@Flobu im using LCD, ill try using your downgrade instruction and report back

**Comment by randomnumgen1** [comment]
@Flobu i was messing about downgrading with that command, changing os update channel and steam client update channel and restarting, as well as using the other steam on the desktop of the steamdeck. on restart of certain steps it gave me the pairing pop-up. but on allowing the connection it gave me a error. after the error it refused other attempts to connect. im guessing the error is a race condition, lock files, way the service communicates with steam.

**Comment by Flobu** [comment]
I got it working by connecting it via LAN and a Dell dockingstation
my guess is that the Wifi in our office blocked some port that is needed for pairing
afterwards it works via wifi fine again

**Comment by gslance** [comment]
I am experiencing the same issues, even on the same network. Unable to register, despite the Steamdeck being in pairing mode.

```
Port 32000 on host 192.168.1.226 is open - latency 22 ms
Port 22 on host 192.168.1.226 is open - latency 14 ms
ssh connection check failed: Authentication failed.
Looking for machine with service name: LanceDeck
Machine IP: 192.168.1.226
Registering with devkit at ip: 192.168.1.226
'LanceDeck': register command failed
Traceback (most recent call last):
  File "C:\Windows\System32\builds\Seqdqh1D\0\devkit\steamos-devkit-internal\client\devkit_client\gui2\gui2.py", line 891, in draw
  File "c:\python312\Lib\concurrent\futures\_base.py", line 449, in result
  File "c:\python312\Lib\concurrent\futures\_base.py", line 401, in __get_result
Exception: devkit approve-ssh-key: please put the Steam client in pairing mode: Settings -> Developer -> Pair new host
```

**Comment by shchavinskyi** [comment]
I had the same issue, but I was eventually able to register the Steam Deck.
I noticed that if you press Register immediately after entering pairing mode on the Steam Deck, the pairing pop-up appears on the device, but the registration fails very quickly without waiting for confirmation.
After a few attempts, I managed to confirm the pairing fast enough and it registered successfully.
Basically, acting very quickly — enter pairing mode, press Register, and immediately confirm on the Steam Deck — worked for me.

**Comment by tctcm** [comment]
> Basically, acting very quickly — enter pairing mode, press Register, and immediately confirm on the Steam Deck — worked for me.

At first, I wasn't even getting the option. But, after doing a system update, this method finally worked after a handful of tries. It's gotta be VERY quick!

**Comment by randomnumgen1** [comment]
confirmed, it works after you do it VERY QUICKLY.

**Comment by gslance** [comment]
Confirmed here as well, and yes you have to be quick. It's not ideal so I hope Valve gets some eyes on it.

**Comment by lostgoat** [comment]
This should be fixed in the latest steam client beta.

**Comment by FeistyOcelot** [comment]
Unfortunately I am still seeing the issue.

Steam OS: 3.7.20
Steam Client Version: 1767909714
Steam Client Build Date: Thu, Jan 8 4:48 PM UTC -05:00

**Comment by matte-schwartz** [comment]
I can also still reproduce this issue with 1767909714, but only on my LCD Deck.

```
Service 'steamdeck' found
  Address is 192.168.1.164:32000
adding steamdeck
Looking for machine with service name: steamdeck
Machine IP: 192.168.1.164
Port 32000 on host 192.168.1.164 is open - latency 4 ms
Port 22 on host 192.168.1.164 is open - latency 107 ms
ssh connection check failed: Authentication failed.
Looking for machine with service name: steamdeck
Machine IP: 192.168.1.164
Registering with devkit at ip: 192.168.1.164
'steamdeck': register command failed
Traceback (most recent call last):
  File "/home/matt/src/valve-src/steamos-devkit/client/devkit_client/gui2/gui2.py", line 978, in draw
    self._result = self.task_future.result()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matt/.pyenv/versions/3.12.9/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/matt/.pyenv/versions/3.12.9/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
Exception: devkit approve-ssh-key: please put the Steam client in pairing mode: Settings -> Developer -> Pair new host
```

[steam-logs-devkit.tar.gz](https://github.com/user-attachments/files/24624673/steam-logs-devkit.tar.gz)

[systemreport-20260114204625.txt](https://github.com/user-attachments/files/24624691/systemreport-20260114204625.txt)

**Comment by matte-schwartz** [comment]
seems to be fixed for me now on the latest beta release (1768528184): https://store.steampowered.com/news/app/1675200/view/373368994105656572?l=english

I was able to pair my LCD Deck

**Comment by FeistyOcelot** [comment]
I can also confirm that this works for me on the latest beta release (1768528184).

**Comment by IoriBranford** [comment]
I also confirm fixed in beta 1768528184, thanks.

**Comment by kisak-valve** [comment]
Closing per the last handful of comments.
