### ISSUE TITLE
It is hard to use modal windows with browser

### ISSUE THREAD

**Issue by slagerfin** [ValveSoftware/SteamOS#270]
When you go see your Profile then select any card badge and then click the "How do I earn card drops?" modal window appears in screen. Because window's position is fixed it is impossible to close this window without lot of zooming and scrolling.

**Comment by not83** [comment]
I believe an option to resize windows like a normal browser

**Comment by ProfessorKaos64** [comment]
If you are talking about popup windows that require you to zoom out, then scroll down to click ok (such as making a report on a post), this has been this way for a long time. It really is something that should be fixed, but I suspect it would require a larger overhaul of the Steam Browser itself.

**Comment by slagerfin** [comment]
Yeah it's the pop-up windows. The original case on the first message won't work after the 161 release, but the problem persists.

**Comment by johnv-valve** [comment]
I think this should no longer be a problem with the new Big Picture UI redesign. If there is some scenario that is still a problem, I recommend posting in the Big Picture group. http://steamcommunity.com/groups/bigpicture/discussions
