### ISSUE TITLE
Desktop with AMD graphics on brewmaster

### ISSUE THREAD

**Issue by tobihan** [ValveSoftware/SteamOS#325]
Hi,

I just read that you ran into the problem that fglrx and GNOME are not working together. This problem also exists in Debian 8:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=722161
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=745901

I posted a workaround here:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=745901#41

Unfortunately this is a massive hack, preloading fglrx for all programs running under GNOME.
It would be really nice if someone could find a cleaner way to fix this that could also be applied in Debian 8. It's a shame that this is not working in a stable release...

EDIT: Actually, the problem should of course be fixed upstream in fglrx or cogl. It's still broken in Debian unstable and other distros. Hope it gets some attention now.

Best,
Tobias

**Comment by johnv-valve** [comment]
Thanks for the excellent information. I did not know this bug also affected Debian and RedHat. I will see what I can do about fixing cogl.

**Comment by waitwhobrokethat** [comment]
Arch Linux had a fix, for the AMD catalyst running Gnome i think.

**Comment by johnv-valve** [comment]
seems like the best info here

https://bugs.archlinux.org/task/35310
https://bugzilla.gnome.org/show_bug.cgi?id=701445

**Comment by wtfrank** [comment]
Good to see from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=745901#41 that is fixed with fglrx 1:15.7-1

**Comment by johnv-valve** [comment]
I've tried the 15.7 driver and it is not fixed. We are in touch with AMD on this issue and as soon as they release a fix we will ship it.

**Comment by TierraDelFuego** [comment]
Is there an issue filed with AMD that can be tracked?

**Comment by johnv-valve** [comment]
Seems to be fixed in the current brewmaster release.

**Comment by not83** [comment]
Thanks!

**Comment by wtfrank** [comment]
I've just tried my brewmaster installation which had an update pending. I applied the update then attempted to exit to desktop which resulted in the same error. I then restarted the machine and tried again and it still resulted in the same error. This is with an AMD HD6430M. Do I need to reinstall brewmaster to pick up the fix?
